local ADDON_NAME, LP = ...
LP.L = LP.L or {}
local L = LP.L

local enUS = {
    ADDON_TITLE = "Loadout Pilot",
    ADDON_SUBTITLE = "Automatic context loadouts",
    CURRENT = "Current",
    CONFIGURE_FOR = "Configure for",
    TALENT_LOADOUT = "Talent loadout",
    EQUIPMENT_SET = "Equipment set",
    CHOOSE_TALENT = "Choose talent loadout...",
    CHOOSE_GEAR = "Choose equipment set...",
    CLEAR = "Clear",
    APPLY_NOW = "Apply mapped loadout now",
    SPECIALIZATION = "Specialization",
    CHOOSE_SPEC = "Choose specialization...",
    AUTO_SPEC_ON = "Spec AUTO: ON",
    AUTO_SPEC_OFF = "Spec AUTO: OFF",
    AUTO_TALENTS_ON = "Talents AUTO: ON",
    AUTO_TALENTS_OFF = "Talents AUTO: OFF",
    AUTO_GEAR_ON = "Gear AUTO: ON",
    AUTO_GEAR_OFF = "Gear AUTO: OFF",
    HUD_ON = "Status HUD: ON",
    HUD_OFF = "Status HUD: OFF",
    HUD_LOCKED = "HUD: LOCKED",
    HUD_UNLOCKED = "HUD: UNLOCKED",
    MINIMAP_ON = "Minimap icon: ON",
    MINIMAP_OFF = "Minimap icon: OFF",
    CHAT_MESSAGES_ON = "Chat messages: ON",
    CHAT_MESSAGES_OFF = "Chat messages: OFF",
    CHAT_MESSAGES_ON_CONFIRM = "Chat notifications enabled.",
    CHAT_MESSAGES_OFF_CONFIRM = "Routine automatic switch messages disabled. Configuration and status feedback will still be shown.",
    RESET_POSITIONS = "Restore positions",
    CLOSE = "Close",
    NO_MAPPING = "Not configured",
    MISSING_LOADOUT = "Saved loadout missing",
    MISSING_GEAR = "Saved equipment set missing",
    READY = "Ready",
    QUEUED_COMBAT = "Queued until combat ends",
    APPLYING = "Applying...",
    ACTION_REQUIRED = "Click Apply",
    TALENTS = "Talents",
    GEAR = "Gear",
    LOOT_SPECIALIZATION = "Loot spec",
    TARGET_LOOT_SPEC = "Target loot spec",
    AUTO = "AUTO",
    MANUAL = "MANUAL",
    CONTEXT_WORLD = "World",
    CONTEXT_DELVE = "Delve",
    CONTEXT_DUNGEON = "Dungeon",
    CONTEXT_MYTHICPLUS = "Mythic+",
    CONTEXT_RAID = "Raid",
    CONTEXT_PVP = "PvP",
    OPEN_SETTINGS = "Right-click to open Loadout Pilot",
    DRAG_HINT = "Drag to move when the HUD is unlocked.",
    MINIMAP_LEFT_CLICK = "Left-click: open or close Loadout Pilot.",
    MINIMAP_RIGHT_CLICK = "Right-click: apply the mapped loadout now.",
    MINIMAP_DRAG_HINT = "Drag: move around the minimap.",
    FIRST_RUN = "Configure specialization, talents, and equipment for each content type. Dungeon-specific overrides are available for advanced rules. Loadout Pilot will switch them automatically whenever WoW allows it.",
    TALENT_MAPPED = "Mapped talent loadout '%s' to %s / %s.",
    GEAR_MAPPED = "Mapped equipment set '%s' to %s / %s.",
    TALENT_CLEARED = "Talent mapping cleared for %s / %s.",
    GEAR_CLEARED = "Equipment mapping cleared for %s / %s.",
    TALENT_SWITCHED = "Talent loadout switched to '%s' for %s.",
    GEAR_SWITCHED = "Equipment set switched to '%s' for %s.",
    WAITING_TALENTS = "WoW is not allowing talent changes right now.",
    TALENT_FAILED = "Talent switch could not be completed automatically. Use Apply when WoW allows the change.",
    GEAR_FAILED = "Equipment switch could not be completed automatically. Use Apply after combat.",
    LOOT_SPEC_SWITCHED = "Loot specialization changed to '%s'.",
    LOOT_SPEC_RESTORED = "Loot specialization restored to '%s'.",
    LOOT_SPEC_APPLYING = "Applying loot specialization...",
    LOOT_SPEC_FAILED = "Loot specialization could not be changed automatically.",
    LOOT_SPEC_UNAVAILABLE = "Loot specialization API is unavailable.",
    NO_TALENTS = "No saved talent loadouts were found for this specialization.",
    NO_GEAR = "No saved equipment sets were found.",
    UNKNOWN = "Unknown",
    STATUS = "Status",
    CLASS_LABEL = "Class",
    SPEC_LABEL = "Spec",
    ROLE_LABEL = "Role",
    GROUP_ROLE = "Group role",
    SPEC_ROLE = "Spec role",
    TARGET_ROLE = "Target role",
    ROLE_DAMAGER = "DPS",
    ROLE_TANK = "Tank",
    ROLE_HEALER = "Healer",
    ROLE_UNKNOWN = "Not assigned",
    ROLE_MISMATCH_STATUS = "Role mismatch: %s -> %s",
    ROLE_MISMATCH_BLOCKED = "Spec switch blocked: protected role is %s, but %s is %s.",
    CONTEXT_LABEL = "Context",
    VERSION = "Version %s - Retail 12.1.0",
    LANGUAGE = "Language",
    ADDON_LANGUAGE = "Addon language",
    LANGUAGE_DESCRIPTION = "Choose the Loadout Pilot language. Automatic follows the WoW client language; unsupported client languages use English.",
    LANGUAGE_AUTO = "Automatic (WoW)",
    LANGUAGE_PTBR = "Portuguese (Brazil)",
    LANGUAGE_EN = "English",
    LANGUAGE_CURRENT = "Current: %s",
    LANGUAGE_BUTTON = "Language: %s",
    LANGUAGE_SAVED = "Language saved as %s. Type /reload to apply it.",
    CANCEL = "Cancel",
    SPEC_MAPPED = "Mapped specialization '%s' to %s.",
    SPEC_CLEARED = "Specialization mapping cleared for %s.",
    BASE_SPEC_CAPTURED = "Saved current specialization '%s' as the %s default so dungeon overrides can return to it.",
    SPEC_SWITCHED = "Specialization switched to '%s'.",
    SPEC_FAILED = "WoW is not allowing the specialization change right now.",
    MISSING_SPEC = "Configured specialization is unavailable.",
    WAITING_SPEC = "Waiting for specialization change.",
    TARGET_SPEC = "Target spec",
    APPLYING_SPEC = "Switching to %s...",
    SPEC_MANUAL_REQUIRED = "Spec change is manual",
    KEEP_CURRENT_SPEC = "Keep current spec (%s)",
    AUTO_SPEC_ON_CONFIRM = "Automatic specialization switching enabled.",
    AUTO_SPEC_OFF_CONFIRM = "Automatic specialization switching disabled.",
    DUNGEON_OVERRIDES = "Dungeon overrides",
    DUNGEON_OVERRIDES_DESCRIPTION = "One override per dungeon applies to Normal, Heroic, Mythic 0, and Mythic+. Unconfigured fields inherit the current Dungeon or Mythic+ default mapping.",
    DUNGEON_LIST = "Dungeons",
    PREVIOUS = "Previous",
    NEXT = "Next",
    USE_CURRENT_DUNGEON = "Select current dungeon",
    NOT_IN_DUNGEON = "You are not currently inside a dungeon.",
    SPECIALIZATION_OVERRIDE = "Specialization override",
    CHOOSE_SPEC_OVERRIDE = "Choose spec override...",
    LOOT_SPEC_OVERRIDE = "Loot specialization override",
    CHOOSE_LOOT_SPEC_OVERRIDE = "Choose loot spec override...",
    CURRENT_SPECIALIZATION_LOOT = "Current specialization (%s)",
    CURRENT_SPECIALIZATION_LOOT_SHORT = "Current specialization",
    NO_OVERRIDE = "No override",
    NO_LOOT_OVERRIDE = "No loot override",
    NO_LOOT_OVERRIDE_ACTIVE = "No override - keep current loot setting",
    INHERIT_DEFAULT = "Inherit default",
    INHERIT = "Inherit",
    TALENT_OVERRIDE = "Talent override",
    CHOOSE_TALENT_OVERRIDE = "Choose talent override...",
    EQUIPMENT_OVERRIDE = "Equipment override",
    CHOOSE_GEAR_OVERRIDE = "Choose gear override...",
    REMOVE_DUNGEON_OVERRIDE = "Remove dungeon override",
    NO_DUNGEON_SELECTED = "No dungeon selected",
    DUNGEON_OVERRIDES_EMPTY = "Enter a dungeon or select one from the list to create a shared Dungeon/Mythic+ override.",
    DUNGEON_SCOPE_LABEL = "Dungeon / Mythic+",
    DUNGEON_FALLBACK_CURRENT = "Current fallback: %s default mapping",
    DUNGEON_FALLBACK_UNIFIED = "Fallback: Dungeon default outside keystones; Mythic+ default during keystone runs",
    INHERITS_VALUE = "Inherit -> %s",
    DUNGEON_TALENT_RESET_FOR_SPEC = "Dungeon talent override cleared because talent loadouts are specialization-specific.",
    OVERRIDE_ACTIVE = "Override active",
    DUNGEON_LABEL = "Dungeon",
    RULE_LABEL = "Rule",
    DUNGEON_OVERRIDE_ACTIVE = "Dungeon override",
    HELP = "Commands: /lpilot, /lpilot apply, /lpilot status, /lpilot overrides, /lpilot spec on|off, /lpilot chat on|off, /lpilot language auto|ptbr|en, /lpilot resetpos, /lpilot debug",
    RESET_POS = "HUD and minimap positions restored.",
    DEBUG_ON = "Debug logging enabled.",
    DEBUG_OFF = "Debug logging disabled.",
}

local ptBR = {
    ADDON_TITLE = "Loadout Pilot",
    ADDON_SUBTITLE = "Loadouts automáticos por contexto",
    CURRENT = "Atual",
    CONFIGURE_FOR = "Configurar para",
    TALENT_LOADOUT = "Loadout de talentos",
    EQUIPMENT_SET = "Conjunto de equipamento",
    CHOOSE_TALENT = "Escolher loadout de talentos...",
    CHOOSE_GEAR = "Escolher conjunto de equipamento...",
    CLEAR = "Limpar",
    APPLY_NOW = "Aplicar loadout mapeado agora",
    SPECIALIZATION = "Especialização",
    CHOOSE_SPEC = "Escolher especialização...",
    AUTO_SPEC_ON = "Spec AUTO: LIGADO",
    AUTO_SPEC_OFF = "Spec AUTO: DESLIGADO",
    AUTO_TALENTS_ON = "Talentos AUTO: LIGADO",
    AUTO_TALENTS_OFF = "Talentos AUTO: DESLIGADO",
    AUTO_GEAR_ON = "Equipamento AUTO: LIGADO",
    AUTO_GEAR_OFF = "Equipamento AUTO: DESLIGADO",
    HUD_ON = "HUD de status: LIGADO",
    HUD_OFF = "HUD de status: DESLIGADO",
    HUD_LOCKED = "HUD: BLOQUEADO",
    HUD_UNLOCKED = "HUD: DESBLOQUEADO",
    MINIMAP_ON = "Ícone no minimapa: LIGADO",
    MINIMAP_OFF = "Ícone no minimapa: DESLIGADO",
    CHAT_MESSAGES_ON = "Mensagens no chat: LIGADO",
    CHAT_MESSAGES_OFF = "Mensagens no chat: DESLIGADO",
    CHAT_MESSAGES_ON_CONFIRM = "Notificações no chat ativadas.",
    CHAT_MESSAGES_OFF_CONFIRM = "Mensagens automáticas de troca desativadas. Confirmações de configuração e status continuarão aparecendo.",
    RESET_POSITIONS = "Restaurar posições",
    CLOSE = "Fechar",
    NO_MAPPING = "Não configurado",
    MISSING_LOADOUT = "Loadout salvo não encontrado",
    MISSING_GEAR = "Conjunto salvo não encontrado",
    READY = "Pronto",
    QUEUED_COMBAT = "Na fila até o combate terminar",
    APPLYING = "Aplicando...",
    ACTION_REQUIRED = "Clique em Aplicar",
    TALENTS = "Talentos",
    GEAR = "Equipamento",
    LOOT_SPECIALIZATION = "Spec de saque",
    TARGET_LOOT_SPEC = "Spec de saque desejada",
    AUTO = "AUTO",
    MANUAL = "MANUAL",
    CONTEXT_WORLD = "Mundo",
    CONTEXT_DELVE = "Imersão",
    CONTEXT_DUNGEON = "Masmorra",
    CONTEXT_MYTHICPLUS = "Mítica+",
    CONTEXT_RAID = "Raide",
    CONTEXT_PVP = "JxJ",
    OPEN_SETTINGS = "Clique com o botão direito para abrir o Loadout Pilot",
    DRAG_HINT = "Arraste para mover quando o HUD estiver desbloqueado.",
    MINIMAP_LEFT_CLICK = "Clique esquerdo: abrir ou fechar o Loadout Pilot.",
    MINIMAP_RIGHT_CLICK = "Clique direito: aplicar o loadout mapeado agora.",
    MINIMAP_DRAG_HINT = "Arraste: mover ao redor do minimapa.",
    FIRST_RUN = "Configure especialização, talentos e equipamento para cada tipo de conteúdo. Overrides por masmorra estão disponíveis para regras avançadas. O Loadout Pilot fará as trocas automaticamente sempre que o WoW permitir.",
    TALENT_MAPPED = "Loadout de talentos '%s' associado a %s / %s.",
    GEAR_MAPPED = "Conjunto de equipamento '%s' associado a %s / %s.",
    TALENT_CLEARED = "Associação de talentos removida para %s / %s.",
    GEAR_CLEARED = "Associação de equipamento removida para %s / %s.",
    TALENT_SWITCHED = "Talentos alterados para '%s' em %s.",
    GEAR_SWITCHED = "Equipamento alterado para '%s' em %s.",
    WAITING_TALENTS = "O WoW não está permitindo alterar talentos agora.",
    TALENT_FAILED = "A troca de talentos não foi concluída automaticamente. Use Aplicar quando o WoW permitir.",
    GEAR_FAILED = "A troca de equipamento não foi concluída automaticamente. Use Aplicar depois do combate.",
    LOOT_SPEC_SWITCHED = "Spec de saque alterada para '%s'.",
    LOOT_SPEC_RESTORED = "Spec de saque restaurada para '%s'.",
    LOOT_SPEC_APPLYING = "Aplicando spec de saque...",
    LOOT_SPEC_FAILED = "A spec de saque não pôde ser alterada automaticamente.",
    LOOT_SPEC_UNAVAILABLE = "A API de spec de saque não está disponível.",
    NO_TALENTS = "Nenhum loadout de talentos salvo foi encontrado para esta especialização.",
    NO_GEAR = "Nenhum conjunto de equipamento salvo foi encontrado.",
    UNKNOWN = "Desconhecido",
    STATUS = "Status",
    CLASS_LABEL = "Classe",
    SPEC_LABEL = "Especialização",
    ROLE_LABEL = "Papel",
    GROUP_ROLE = "Papel no grupo",
    SPEC_ROLE = "Papel da spec",
    TARGET_ROLE = "Papel da spec desejada",
    ROLE_DAMAGER = "DPS",
    ROLE_TANK = "Tank",
    ROLE_HEALER = "Healer",
    ROLE_UNKNOWN = "Não definido",
    ROLE_MISMATCH_STATUS = "Papel incompatível: %s -> %s",
    ROLE_MISMATCH_BLOCKED = "Troca de spec bloqueada: o papel protegido é %s, mas %s é %s.",
    CONTEXT_LABEL = "Contexto",
    VERSION = "Versão %s - Retail 12.1.0",
    LANGUAGE = "Idioma",
    ADDON_LANGUAGE = "Idioma do addon",
    LANGUAGE_DESCRIPTION = "Escolha o idioma do Loadout Pilot. Automático segue o idioma do cliente do WoW; idiomas ainda não traduzidos usam inglês.",
    LANGUAGE_AUTO = "Automático (WoW)",
    LANGUAGE_PTBR = "Português (Brasil)",
    LANGUAGE_EN = "English",
    LANGUAGE_CURRENT = "Atual: %s",
    LANGUAGE_BUTTON = "Idioma: %s",
    LANGUAGE_SAVED = "Idioma salvo como %s. Digite /reload para aplicar.",
    CANCEL = "Cancelar",
    SPEC_MAPPED = "Especialização '%s' associada a %s.",
    SPEC_CLEARED = "Associação de especialização removida para %s.",
    BASE_SPEC_CAPTURED = "A spec atual '%s' foi salva como padrão de %s para que os overrides de masmorra possam voltar para ela.",
    SPEC_SWITCHED = "Especialização alterada para '%s'.",
    SPEC_FAILED = "O WoW não está permitindo trocar de especialização agora.",
    MISSING_SPEC = "A especialização configurada não está disponível.",
    WAITING_SPEC = "Aguardando troca de especialização.",
    TARGET_SPEC = "Spec desejada",
    APPLYING_SPEC = "Trocando para %s...",
    SPEC_MANUAL_REQUIRED = "Troca de spec manual",
    KEEP_CURRENT_SPEC = "Manter spec atual (%s)",
    AUTO_SPEC_ON_CONFIRM = "Troca automática de especialização ativada.",
    AUTO_SPEC_OFF_CONFIRM = "Troca automática de especialização desativada.",
    DUNGEON_OVERRIDES = "Overrides de masmorra",
    DUNGEON_OVERRIDES_DESCRIPTION = "Um único override por masmorra vale para Normal, Heroico, Mítico 0 e Mítica+. Campos não configurados herdam o mapeamento padrão atual de Masmorra ou Mítica+.",
    DUNGEON_LIST = "Masmorras",
    PREVIOUS = "Anterior",
    NEXT = "Próxima",
    USE_CURRENT_DUNGEON = "Selecionar masmorra atual",
    NOT_IN_DUNGEON = "Você não está dentro de uma masmorra agora.",
    SPECIALIZATION_OVERRIDE = "Override de especialização",
    CHOOSE_SPEC_OVERRIDE = "Escolher override de spec...",
    LOOT_SPEC_OVERRIDE = "Override de spec de saque",
    CHOOSE_LOOT_SPEC_OVERRIDE = "Escolher override de spec de saque...",
    CURRENT_SPECIALIZATION_LOOT = "Especialização atual (%s)",
    CURRENT_SPECIALIZATION_LOOT_SHORT = "Especialização atual",
    NO_OVERRIDE = "Sem override",
    NO_LOOT_OVERRIDE = "Sem override de saque",
    NO_LOOT_OVERRIDE_ACTIVE = "Sem override - manter configuração de saque atual",
    INHERIT_DEFAULT = "Herdar padrão",
    INHERIT = "Herdar",
    TALENT_OVERRIDE = "Override de talentos",
    CHOOSE_TALENT_OVERRIDE = "Escolher override de talentos...",
    EQUIPMENT_OVERRIDE = "Override de equipamento",
    CHOOSE_GEAR_OVERRIDE = "Escolher override de equipamento...",
    REMOVE_DUNGEON_OVERRIDE = "Remover override da masmorra",
    NO_DUNGEON_SELECTED = "Nenhuma masmorra selecionada",
    DUNGEON_OVERRIDES_EMPTY = "Entre em uma masmorra ou escolha uma da lista para criar um override compartilhado entre Masmorra e Mítica+.",
    DUNGEON_SCOPE_LABEL = "Masmorra / Mítica+",
    DUNGEON_FALLBACK_CURRENT = "Fallback atual: mapeamento padrão de %s",
    DUNGEON_FALLBACK_UNIFIED = "Fallback: padrão de Masmorra fora de pedras; padrão de Mítica+ durante pedras",
    INHERITS_VALUE = "Herda -> %s",
    DUNGEON_TALENT_RESET_FOR_SPEC = "O override de talentos da masmorra foi limpo porque loadouts de talentos pertencem a uma especialização.",
    OVERRIDE_ACTIVE = "Override ativo",
    DUNGEON_LABEL = "Masmorra",
    RULE_LABEL = "Regra",
    DUNGEON_OVERRIDE_ACTIVE = "Override da masmorra",
    HELP = "Comandos: /lpilot, /lpilot apply, /lpilot status, /lpilot overrides, /lpilot spec on|off, /lpilot chat on|off, /lpilot language auto|ptbr|en, /lpilot resetpos, /lpilot debug",
    RESET_POS = "Posições do HUD e do minimapa restauradas.",
    DEBUG_ON = "Log de debug ativado.",
    DEBUG_OFF = "Log de debug desativado.",
}

local clientLocale = (GetLocale and GetLocale()) or "enUS"
local localeOverride = "auto"
local locale = clientLocale

local function NormalizeLanguageOverride(value)
    value = tostring(value or "auto")
    local lower = string.lower(value)
    if lower == "ptbr" or lower == "pt" or lower == "portuguese" or lower == "portugues" then
        return "ptBR"
    end
    if lower == "enus" or lower == "engb" or lower == "en" or lower == "english" then
        return "enUS"
    end
    return "auto"
end

local function ResolveEffectiveLocale(override)
    override = NormalizeLanguageOverride(override)
    local resolved = override == "auto" and clientLocale or override
    if resolved ~= "ptBR" then resolved = "enUS" end
    return resolved, override
end

if type(_G.LoadoutPilotDB) == "table" then
    locale, localeOverride = ResolveEffectiveLocale(_G.LoadoutPilotDB.languageOverride)
else
    locale, localeOverride = ResolveEffectiveLocale("auto")
end

setmetatable(L, {
    __index = function(_, key)
        local active = locale == "ptBR" and ptBR or enUS
        return active[key] or enUS[key] or key
    end,
})

function LP:T(key, ...)
    local text = L[key] or key
    if select("#", ...) > 0 then
        local ok, formatted = pcall(string.format, text, ...)
        if ok then return formatted end
    end
    return text
end

function LP.SetLocaleOverride(value)
    locale, localeOverride = ResolveEffectiveLocale(value)
    LP.locale = locale
    LP.rawLocale = clientLocale
    LP.languageOverride = localeOverride
    return locale
end

function LP.GetLocaleOverride()
    return localeOverride
end

function LP.GetClientLocale()
    return clientLocale
end

LP.SetLocaleOverride(localeOverride)
